version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d21o897diees73e1vlhg-a.oregon-postgres.render.com/zarpas
      - SPRING_DATASOURCE_USERNAME=zarpas_user
      - SPRING_DATASOURCE_PASSWORD=1JvEF5280asP6pxeqYvd8Zs0VaKZqGFR
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: zarpas_user
      POSTGRES_PASSWORD: 1JvEF5280asP6pxeqYvd8Zs0VaKZqGFR
      POSTGRES_DB: zarpas
    ports:
      - "5432:5432"